### ISSUE TITLE
 Pre fill contact information

### ISSUE THREAD

**Issue by angelofonseca1990** [jpfperondini/cordova-add-contact#3]
I wonder if can pass information like a phone number to appear in the Add Contact in native view?

**Comment by jpfperondini** [comment]
It is possible on android.

@pgneri, can you help us with the iOS support?

This feature is on the roadmap but i can't give a due date.

Feel free to submit a pull request

**Comment by pgneri** [comment]
It is possible in iOS too. I can support and help in development this solution. 

Case you need help to development on iOS, contact myself, else also submit a pull request this. 

Ps: I apologize for not being word-perfect in English. :)

**Comment by jpfperondini** [comment]
OK. Give some days to do the JS/Android stuff

**Comment by jpfperondini** [comment]
Sorry for the delayed response.

The android support was added.

**Comment by jpfperondini** [comment]
ios support added
